# Generated by Django 3.0.5 on 2020-04-21 10:29

from django.db import migrations, models
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='col',
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=isbn_field.fields.ISBNField(max_length=28, null=True, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN'),
        ),
    ]
